### ISSUE TITLE
Travis build fails on JDK 6

### ISSUE THREAD

**Issue by sjrd** [scala-js/closure-compiler#2]
https://travis-ci.org/scala-js/closure-compiler/builds/142710426

**Comment by nicolasstucki** [comment]
The issue is that `CommandLineRunnerTest` was not rewritten with Java 6 because `CommandLineRunner` is missing [part of its implementation](https://github.com/scala-js/closure-compiler/blob/java-6/src/com/google/javascript/jscomp/CommandLineRunner.java#L1693-L1696) Java 6. We did not really care about this entry point for Scala.js and therefore left it unimplemented for now.

**Comment by sjrd** [comment]
Closing as I'm about to archive this repository.
